services:
 redis:
   image: redis:6.2
   container_name: recruiter-dev-redis
   ports:
     - "6379:6379"
   volumes:
     - redis_data:/data
 selenium:
   image: selenium/standalone-firefox:latest
   container_name: recruiter-dev-selenium
   ports:
     - "14440:4444"
   environment:
     - SE_NODE_ENABLE_MANAGED_DOWNLOADS=true
     - SE_OPTS=--enable-managed-downloads true
     - SE_LOG_LEVEL=INFO
   #      - SE_BROWSER_ARGS_INCOGNITO=--incognitos
   restart: always
   shm_size: 4gb
 backend:
   build:
     context: ./backend
   container_name: recruiter-dev-backend
   command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 7013
   ports:
     - "18000:7013"
   volumes:
     - ./backend:/app
   depends_on:
     - redis
     - selenium
   environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - FASTAPI_HOST=backend
     - FASTAPI_PORT=7013
     - BASE_BOOKS_URL=https://books.toscrape.com/
     - BASE_NEWS_URL=https://news.ycombinator.com/
     - MAX_PRICE=20  
     - MIN_BOOKS=50  
     - MAX_BOOKS=100 

 frontend:
   build:
     context: ./frontend
   container_name: recruiter-dev-frontend
   ports:
     - "3000:3000"
   volumes:
     - ./frontend/src:/app/src
   depends_on:
    - n8n
 n8n:
   image: n8nio/n8n
   container_name: recruiter-dev-n8n
   ports:
     - "5678:5678"
   environment:
     - N8N_BASIC_AUTH_ACTIVE=true
     - N8N_BASIC_AUTH_USER=admin
     - N8N_BASIC_AUTH_PASSWORD=admin
     - N8N_HOST=n8n
     - N8N_PORT=5678
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - N8N_SECURE_COOKIE=false
   volumes:
     - n8n_data:/home/node/.n8n
   depends_on:
     - redis
     - backend


volumes:
 redis_data:
 n8n_data: