FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    wget \
    firefox-esr \
    && rm -rf /var/lib/apt/lists/*

RUN LATEST_RELEASE=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest) \
    && VERSION=$(echo "$LATEST_RELEASE" | grep -Po '"tag_name": "\K.*?(?=")') \
    && DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | grep -Po '"browser_download_url": "\K.*?(?=")' | grep linux64) \
    && echo "Instalando Geckodriver $VERSION desde $DOWNLOAD_URL" \
    && wget -O geckodriver.tar.gz "$DOWNLOAD_URL" \
    && tar -xzf geckodriver.tar.gz -C /usr/local/bin \
    && chmod +x /usr/local/bin/geckodriver \
    && geckodriver --version \
    && rm geckodriver.tar.gz

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

COPY . .

EXPOSE 7013